# Generated by Django 5.2.9 on 2026-01-09 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='project owner'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', 'created_at'], name='projects_pr_user_id_29bec8_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', 'deleted_at'], name='projects_pr_user_id_103a64_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='unique_project_title_per_user'),
        ),
    ]
