# Generated by Django 5.2.9 on 2026-01-14 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_historicalproject'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='project',
            name='projects_pr_deleted_4c0d8c_idx',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='deleted_at',
        ),
    ]
